version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/db
    volumes:
      - ./db:/db
    ports:
      - 27017:27017

  port_domain_service:
    build:
      context: ./
      dockerfile: PortDomainService/Dockerfile
    environment:
      - PORT=:5001
      - MONGO_URI=mongodb://mongodb:27017
      - DB=portsDB
      - COLLECTION=ports
    ports:
      - 5001:5001
    depends_on:
      - mongodb

  client_api:
    build:
      context: ./
      dockerfile: ClientAPI/Dockerfile
    environment:
      - PORT=:5000
      - PORT_DOMAIN_SERVICE_URI=port_domain_service:5001
    ports:
      - 5000:5000
    depends_on:
      - port_domain_service
      - mongodb
